.\" Manpage for neat.
.TH alfa 1 "22 Apr 2016" "1.0" "alfa man page"
.SH NAME
alfa \- automated line fitting algorithm
.SH SYNOPSIS
alfa [\fIOPTION\fR] [\fIVALUE\fR]... [\fIFILE\fR]
.SH DESCRIPTION
\fBalfa\fR rapidly fits deep emission line spectra, using a genetic algorithm to optimise fitting parameters.  It has a number of configurable parameters, and while the default values should work well in many situations, a good fit to your observed spectrum may require some adjustments.
.PP
\fBalfa\fR reads one dimensional spectra in either plain text or FITS format.  Plain text input should consist of two columns, giving wavelength and flux.  It can also read data cubes and row-stacked spectra in FITS format.  Results are written out in plain text, to files containing the fit (total fit, continuum-subtracted original, continuum, sky lines and residuals), and the line flux measurements.
.SH OPTIONS
.TP
.B \-n, \-\-normalise [VALUE]
normalise to Hb=100 assuming that F(Hb)=\fIVALUE\fR.  If \fIVALUE\fR is zero, no normalisation is applied.  If this option is not specified, fluxes are normalised using the measured value of Hb if it is detected, and not normalised otherwise.
.TP
.B \-vg, \-\-velocity\-guess [VALUE]
initial guess for the velocity of the object [km/s]. Default: 0.
.TP
.B \-rg, \-\-resolution\-guess [VALUE]
initial guess for the resolution [lambda/delta lambda]. Default: estimated using the sampling of the input spectrum, assuming that it is Nyquist sampled.
.TP
.B \-vtol1, \-\-velocity\-tolerance\-1 [VALUE]
variation allowed in velocity in first pass of the fitting. Default: 900km/s
.TP
.B \-vtol2, \-\-velocity\-tolerance\-2 [VALUE]
variation allowed in velocity in second pass of the fitting. Default: 60km/s
.TP
.B \-rtol1, \-\-resolution\-tolerance\-1 [VALUE]
variation allowed in resolution in first pass. Default: equal to 0.9 x resolution guess
.TP
.B \-rtol2, \-\-resolution\-tolerance\-2 [VALUE]
variation allowed in resolution in second pass. Default: 500.
.TP
.B \-ss, \-\-subtract\-sky
fit and subtract night sky emission lines before fitting nebular emission lines
.TP
.B \-o, \-\-output\-dir
the directory in which to put the output files. Default: current working directory
.TP
.B \-skycat, \-strongcat, \-deepcat
the files containing the line catalogues to be used for the removal of sky lines, the estimation of velocity and resolution, and the full line fitting.  The default catalogues are stored in /etc/alfa
.TP
.B \-g, \-\-generations
the number of generations used in the genetic algorithm. Default: 500
.TP
.B \-ps, \-\-populationsize
The size of the population used in the genetic algorithm. Default: 30
.TP
.B \-pr, \-\-pressure
The fraction of the population retained from each generation. Default: 0.3
.SH SEE ALSO
neat
.SH BUGS
No known bugs.
.SH AUTHOR
Roger Wesson
